management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: false
    fetch-registry: true
    register-with-eureka: false
spring:
  redis:
    host: 127.0.0.1
    port: '6379'
